// <auto-generated />
using System.Numerics;
using Microsoft.Maui.Graphics;

namespace Zuaros.Intro;

// Generated by scripts/generate-brand.mjs from src/brand/zuaros-master.svg.
public static partial class ZuarosGeometry
{
    public const string CoreViewBox = "0 0 64 64";
    public const string CoreBodySvgPath = "M8 12H41L47 18L21 45H49V54H8V45L35 21H8Z";
    public const string CoreSparkSvgPath = "M47 9L52 4L59 11L54 16Z";
    internal const float CenterX = 50f;
    internal const float CenterY = 50f;
    internal const float WordmarkCanvasHeight = 116.666667f;

    internal static readonly OrbitDefinition[] Orbits =
    {
        new(30.833333f, 30.833333f, 0f),
        new(39.333333f, 19.333333f, -38f),
        new(39.333333f, 19.333333f, 38f),
        new(15f, 39.166667f, 38f),
    };

    internal static readonly ParticleDefinition[] Particles =
    {
        new(0, 14f, 0.06f, 1f, 0.583333f, 1f, 0.52f),
        new(1, 19f, 0.43f, -1f, 0.45f, 0.78f, 0.46f),
        new(2, 25f, 0.74f, 1f, 0.366667f, 0.62f, 0.64f),
        new(3, 31f, 0.21f, -1f, 0.266667f, 0.42f, 0.42f),
    };

    internal static readonly PathF[] OrbitPaths = CreateOrbitPaths();
    internal static readonly PathF CoreBodyPath = CreateCoreBodyPath();
    internal static readonly PathF CoreSparkPath = CreateCoreSparkPath();
    internal static readonly PathF WordmarkPath = CreateWordmarkPath();

    private static PathF CreateCoreBodyPath()
    {
        PathF path = new();
        path.MoveTo(8f, 12f);
        path.LineTo(41f, 12f);
        path.LineTo(47f, 18f);
        path.LineTo(21f, 45f);
        path.LineTo(49f, 45f);
        path.LineTo(49f, 54f);
        path.LineTo(8f, 54f);
        path.LineTo(8f, 45f);
        path.LineTo(35f, 21f);
        path.LineTo(8f, 21f);
        path.Close();
        TransformCore(path);
        return path;
    }

    private static PathF CreateCoreSparkPath()
    {
        PathF path = new();
        path.MoveTo(47f, 9f);
        path.LineTo(52f, 4f);
        path.LineTo(59f, 11f);
        path.LineTo(54f, 16f);
        path.Close();
        TransformCore(path);
        return path;
    }

    private static void TransformCore(PathF path)
    {
        Matrix3x2 transform =
            Matrix3x2.CreateScale(0.533333f) *
            Matrix3x2.CreateTranslation(33.333333f, 33f) *
            Matrix3x2.CreateRotation(-7f * MathF.PI / 180f, new Vector2(CenterX, CenterY));
        path.Transform(transform);
    }

    private static PathF CreateWordmarkPath()
    {
        PathF path = new();
        path.MoveTo(4f, 12f);
        path.LineTo(24f, 12f);
        path.LineTo(4f, 34f);
        path.LineTo(25f, 34f);

        path.MoveTo(37f, 12f);
        path.LineTo(37f, 26f);
        path.QuadTo(37f, 35f, 46f, 35f);
        path.QuadTo(55f, 35f, 55f, 26f);
        path.LineTo(55f, 12f);

        path.MoveTo(86f, 34f);
        path.LineTo(86f, 12f);

        path.MoveTo(85f, 17f);
        path.QuadTo(82f, 11f, 76f, 11f);
        path.QuadTo(65f, 11f, 65f, 23f);
        path.QuadTo(65f, 35f, 76f, 35f);
        path.QuadTo(82f, 35f, 85f, 29f);

        path.MoveTo(99f, 34f);
        path.LineTo(99f, 13f);
        path.MoveTo(99f, 21f);
        path.QuadTo(102f, 11f, 113f, 12f);

        path.MoveTo(133f, 11f);
        path.QuadTo(122f, 11f, 122f, 23f);
        path.QuadTo(122f, 35f, 133f, 35f);
        path.QuadTo(144f, 35f, 144f, 23f);
        path.QuadTo(144f, 11f, 133f, 11f);
        path.Close();

        path.MoveTo(173f, 14f);
        path.QuadTo(169f, 11f, 164f, 11f);
        path.QuadTo(154f, 11f, 154f, 17f);
        path.QuadTo(154f, 22f, 164f, 23f);
        path.QuadTo(174f, 24f, 174f, 29f);
        path.QuadTo(174f, 35f, 164f, 35f);
        path.QuadTo(158f, 35f, 153f, 31f);
        path.Transform(
            Matrix3x2.CreateScale(0.37f) *
            Matrix3x2.CreateTranslation(17f, 98.333333f));
        return path;
    }
}
